name: Pipeline

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs: 
  Pipeline:
    uses: Mottu-ops/pipeline-core/.github/workflows/container-nodejs-kubernetes.yaml@v2
    with:
      app_name: operation-planning-bff
      namespace: attendance
      bu: rental-bu
    secrets: inherit 
