name: Require Checklist

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

jobs:
  PR_Checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
